name: example-enviroment
channels:
  - conda-forge
dependencies:
  - pip:
    - setuptools
    - matplotlib
    - DateTime
    - argparse
    - MarkDown
    - urllib
    - affine
  - python
  - numpy
  - pandas
  - scipy
  - obspy
  - gdal
  - cartopy
  - rasterio
